application:
  subdomain: bestsub
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://bestsub:8080/
services:
  bestsub:
    # upstream: ghcr.io/bestruirui/bestsub:v2.0.5
    image: ghcr.1ms.run/bestruirui/bestsub:v2.0.5
    binds:
      - /lzcapp/var/data:/app/data
